config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  post '/home/index' => 'home#index' , as: :home_index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    flash[:error] = flash[:success] = ''
    if request.post?
      begin
        json_payload = { status: params[:status].to_i,
                         priority: params[:priority].to_i,
                         description: params[:description],
                         subject: params[:subject],
                         cc_emails: params[:cc_email].split(','),
                         email: params[:email] }.to_json

        freshdesk_api_url = "https://#{params[:freshdesk_domain]}.freshdesk.com/api/v2/tickets"

        site = RestClient::Resource.new(freshdesk_api_url, params[:api_key], 'X')
        response = site.post(json_payload, content_type: 'application/json')
        puts "response_code: #{response.code} \n Location Header:" \
             "#{response.headers[:location]}\n response_body: #{response.body}"
        flash[:success] = 'API Success: Your request is successful.'
      rescue StandardError => e
        flash[:error] = 'API Error: Your request is not successful.'
        puts e.message
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div style="text-align: center;">
  <h1> Fresh Desk API Request </h1>
  <%= form_tag home_index_path do %>
    <% if (flash[:error] || flash[:success]).present? %>
      <%= flash[:error] || flash[:success] %>
    <% end %>
    <br>
    <%= label_tag(:freshdesk_domain) %>
    <br>
    <%= text_field_tag(:freshdesk_domain) %>
    <br>
    <br>
    <%= label_tag(:api_key) %>
    <br>
    <%= text_field_tag(:api_key) %>
    <br>
    <br>
    <%= label_tag(:email) %>
    <br>
    <%= text_field_tag(:email) %>
    <br>
    <br>
    <%= label_tag(:status) %>
    <br>
    <%= select_tag(:status, options_for_select([["2",2],["3",3],["4",4], ["5", 5], ['6', 6], ['7', 7]], params[:status] ), class:"select") %>
    <br>
    <br>
    <%= label_tag(:priority) %>
    <br>
    <%= select_tag(:priority, options_for_select([["1",1],["2",2],["3",3], ["4", 4]], params[:priority] ), class:"select") %>
    <br>
    <br>
    <%= label_tag(:subject) %>
    <br>
    <%= text_field_tag(:subject) %>
    <br>
    <br>
    <%= label_tag(:description) %>
    <br>
    <%= text_area_tag(:description) %>
    <br>
    <br>
    <%= label_tag(:cc_email) %>
    <br>
    <%= text_field_tag(:cc_email) %>
    <br>
    <br>
    <%= submit_tag("Submit") %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stripe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>